# Generated by Django 2.1.1 on 2018-11-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
        ('Rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('voted_amount', models.IntegerField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Post.Post')),
            ],
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='RatingList',
        ),
    ]
